# Generated by Django 5.1.2 on 2024-11-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_mbti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='curso',
            field=models.TextField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
