# Generated by Django 5.1.2 on 2024-11-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste_mbti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostas',
            name='perfil_MBTI',
            field=models.TextField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respostas',
            name='pergunta_1',
            field=models.TextField(max_length=11),
        ),
        migrations.AlterField(
            model_name='respostas',
            name='pergunta_2',
            field=models.TextField(max_length=11),
        ),
        migrations.AlterField(
            model_name='respostas',
            name='pergunta_3',
            field=models.TextField(max_length=13),
        ),
        migrations.AlterField(
            model_name='respostas',
            name='pergunta_4',
            field=models.TextField(max_length=13),
        ),
    ]
