# Generated by Django 5.1.2 on 2024-11-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste_mbti', '0002_respostas_perfil_mbti_alter_respostas_pergunta_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostas',
            name='perfil_MBTI',
            field=models.TextField(),
        ),
    ]
