# Generated by Django 5.1.2 on 2024-11-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste_mbti', '0003_alter_respostas_perfil_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostas',
            name='perfil_MBTI',
            field=models.TextField(max_length=2),
        ),
    ]
