# Generated by Django 5.1.2 on 2024-11-13 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_mbti', '0002_cadastro_curso'),
        ('teste_mbti', '0004_alter_respostas_perfil_mbti'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostas',
            name='chave',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth_mbti.cadastro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respostas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
